# AI-customer-support-agent\packages\knowledge\repositories\embedding_repository.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from packages.knowledge.domain.embedding import KnowledgeChunkEmbedding
from packages.knowledge.embeddings.models import EmbeddingInputDescriptor, EmbeddingProviderDescriptor

@dataclass(frozen=True, slots=True)
class KnowledgeVersionEmbeddingCoverage:
    """
    Authoritative embedding coverage for one knowledge version under one exact embedding-provider and input-strategy profile.

    Embeddings generated by another provider, model, model revision, dimensionality, input strategy, strategy version, or configuration
    fingerprint do not contribute to embedded_chunk_count.
    """
    total_chunk_count: int
    embedded_chunk_count: int

    def __post_init__(self) -> None:
        for field_name, value in (("total_chunk_count", self.total_chunk_count), ("embedded_chunk_count", self.embedded_chunk_count),):
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError(f"{field_name} must be an integer.")

            if value < 0:
                raise ValueError(f"{field_name} must not be negative.")

        if self.embedded_chunk_count > self.total_chunk_count:
            raise ValueError("embedded_chunk_count cannot exceed total_chunk_count."            )

    @property
    def is_fully_embedded(self) -> bool:
        """
        Zero chunks must never be considered fully embedded.
        """
        return (
            self.total_chunk_count > 0
            and self.embedded_chunk_count
            == self.total_chunk_count
        )


class KnowledgeEmbeddingRepository(Protocol):
    """
    Persistence contract for model-dependent knowledge embedding artifacts.

    Implementations participate in the surrounding Unit of Work and must not commit transactions independently.
    """
    def add(self, embedding: KnowledgeChunkEmbedding) -> None:
        """Persist one newly generated embedding artifact."""
        ...

    def add_many(self, embeddings: list[KnowledgeChunkEmbedding]) -> None:
        """
        Persist multiple embedding artifacts as part of the surrounding transaction.
        """
        ...

    def add_many_if_absent(self, embeddings: list[KnowledgeChunkEmbedding]) -> int:
        """
        Persist only embedding artifacts that do not already exist.

        Returns the number of artifacts actually inserted.

        Implementations must not commit.
        """
        ...

    def get_by_id(self, embedding_id: UUID) -> KnowledgeChunkEmbedding | None:
        """Return an embedding artifact by identity, or None."""
        ...

    def list_for_chunk(self, chunk_id: UUID) -> list[KnowledgeChunkEmbedding]:
        """Return all embedding artifacts associated with a chunk."""
        ...

    def list_for_chunks(self, chunk_ids: list[UUID], *, provider: EmbeddingProviderDescriptor, input_descriptor: EmbeddingInputDescriptor) -> list[KnowledgeChunkEmbedding]:
        """
        Return existing artifacts for the supplied chunks under one exact embedding profile.

        Used by embedding workflows to avoid regenerating artifacts that already exist.
        """
        ...

    def get_coverage_for_version(self, version_id: UUID, *, provider: EmbeddingProviderDescriptor, input_descriptor: EmbeddingInputDescriptor) -> KnowledgeVersionEmbeddingCoverage:
        """
        Return aggregate embedding coverage for one version.

        The implementation must:

        - count all canonical chunks belonging to version_id;
        - count distinct chunks having an embedding matching the exact supplied provider and input descriptors;
        - ignore embeddings created with any other profile;
        - return zero counts when the version contains no chunks;
        - execute as one aggregate database query;
        - never commit the surrounding transaction.
        """
        ...