"""add knowledge management tables

Revision ID: 1842440b0b73
Revises: 53167f87b96c
Create Date: 2026-08-29 03:43:18.285941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1842440b0b73'
down_revision: Union[str, Sequence[str], None] = '53167f87b96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'active'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'active'\n                AND archived_at IS NULL\n                AND deleted_at IS NULL\n            )\n            OR\n            (\n                status = 'archived'\n                AND archived_at IS NOT NULL\n                AND deleted_at IS NULL\n            )\n            OR\n            (\n                status = 'deleted'\n                AND deleted_at IS NOT NULL\n            )\n            ", name=op.f('ck_knowledge_documents_ck_knowledge_documents_lifecycle')),
    sa.CheckConstraint("content_type IN ('policy', 'faq', 'procedure', 'guide', 'reference', 'other')", name=op.f('ck_knowledge_documents_ck_knowledge_documents_content_type')),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')", name=op.f('ck_knowledge_documents_ck_knowledge_documents_status')),
    sa.CheckConstraint("visibility IN ('customer', 'internal', 'both')", name=op.f('ck_knowledge_documents_ck_knowledge_documents_visibility')),
    sa.CheckConstraint('archived_at IS NULL OR archived_at >= created_at', name=op.f('ck_knowledge_documents_ck_knowledge_documents_archived_at_order')),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_at >= created_at', name=op.f('ck_knowledge_documents_ck_knowledge_documents_deleted_at_order')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_knowledge_documents_ck_knowledge_documents_title_not_blank')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_knowledge_documents_ck_knowledge_documents_timestamp_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_documents_content_type', 'knowledge_documents', ['content_type'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_documents_created_at', 'knowledge_documents', ['created_at'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_documents_status', 'knowledge_documents', ['status'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_documents_visibility', 'knowledge_documents', ['visibility'], unique=False, schema='knowledge')
    op.create_table('knowledge_document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('ingestion_status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=200), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_ingestion_status')),
    sa.CheckConstraint("source_type IN ('markdown', 'plain_text', 'pdf', 'docx', 'html', 'rich_text')", name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_source_type')),
    sa.CheckConstraint("status IN ('draft', 'processing', 'ready', 'published', 'superseded', 'failed', 'archived')", name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_status')),
    sa.CheckConstraint('length(btrim(content_hash)) > 0', name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_hash_not_blank')),
    sa.CheckConstraint('length(btrim(source_content)) > 0', name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_content_not_blank')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_timestamp_order')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_positive_version')),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge.knowledge_documents.id'], name=op.f('fk_knowledge_document_versions_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_knowledge_document_versions_document_version'),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_document_versions_document_id', 'knowledge_document_versions', ['document_id'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_document_versions_ingestion_status', 'knowledge_document_versions', ['ingestion_status'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_document_versions_status', 'knowledge_document_versions', ['status'], unique=False, schema='knowledge')
    op.create_index('uq_knowledge_document_versions_published', 'knowledge_document_versions', ['document_id'], unique=True, schema='knowledge', postgresql_where=sa.text("status = 'published'"))
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                start_offset IS NULL\n                AND end_offset IS NULL\n            )\n            OR\n            (\n                start_offset IS NOT NULL\n                AND end_offset IS NOT NULL\n                AND start_offset >= 0\n                AND end_offset > start_offset\n            )\n            ', name=op.f('ck_knowledge_chunks_ck_knowledge_chunks_valid_offsets')),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_knowledge_chunks_ck_knowledge_chunks_nonnegative_index')),
    sa.CheckConstraint('length(btrim(content)) > 0', name=op.f('ck_knowledge_chunks_ck_knowledge_chunks_content_not_blank')),
    sa.CheckConstraint('token_count IS NULL OR token_count > 0', name=op.f('ck_knowledge_chunks_ck_knowledge_chunks_positive_token_count')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_knowledge_chunks_ck_knowledge_chunks_timestamp_order')),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge.knowledge_document_versions.id'], name=op.f('fk_knowledge_chunks_version_id_knowledge_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks')),
    sa.UniqueConstraint('version_id', 'chunk_index', name='uq_knowledge_chunks_version_index'),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_chunks_version_id', 'knowledge_chunks', ['version_id'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_version_id', table_name='knowledge_chunks', schema='knowledge')
    op.drop_table('knowledge_chunks', schema='knowledge')
    op.drop_index('uq_knowledge_document_versions_published', table_name='knowledge_document_versions', schema='knowledge', postgresql_where=sa.text("status = 'published'"))
    op.drop_index('ix_knowledge_document_versions_status', table_name='knowledge_document_versions', schema='knowledge')
    op.drop_index('ix_knowledge_document_versions_ingestion_status', table_name='knowledge_document_versions', schema='knowledge')
    op.drop_index('ix_knowledge_document_versions_document_id', table_name='knowledge_document_versions', schema='knowledge')
    op.drop_table('knowledge_document_versions', schema='knowledge')
    op.drop_index('ix_knowledge_documents_visibility', table_name='knowledge_documents', schema='knowledge')
    op.drop_index('ix_knowledge_documents_status', table_name='knowledge_documents', schema='knowledge')
    op.drop_index('ix_knowledge_documents_created_at', table_name='knowledge_documents', schema='knowledge')
    op.drop_index('ix_knowledge_documents_content_type', table_name='knowledge_documents', schema='knowledge')
    op.drop_table('knowledge_documents', schema='knowledge')
    # ### end Alembic commands ###
