"""add conversation start idempotency

Revision ID: 2c27647aaa28
Revises: e276f083ae3c
Create Date: 2026-09-17 17:31:21.476565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c27647aaa28'
down_revision: Union[str, Sequence[str], None] = 'e276f083ae3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_start_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='accepted', nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_message_id', sa.UUID(), nullable=False),
    sa.Column('latest_ai_run_id', sa.UUID(), nullable=True),
    sa.Column('processing_token', sa.UUID(), nullable=True),
    sa.Column('processing_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'accepted'\n                AND processing_token IS NULL\n                AND processing_expires_at IS NULL\n                AND completed_at IS NULL\n                AND response_snapshot IS NULL\n            )\n            OR\n            (\n                status = 'processing'\n                AND processing_token IS NOT NULL\n                AND processing_expires_at IS NOT NULL\n                AND completed_at IS NULL\n                AND response_snapshot IS NULL\n                AND attempt_count > 0\n            )\n            OR\n            (\n                status IN ('completed', 'failed')\n                AND processing_token IS NULL\n                AND processing_expires_at IS NULL\n                AND completed_at IS NOT NULL\n                AND response_snapshot IS NOT NULL\n                AND attempt_count > 0\n            )\n            ", name=op.f('ck_conversation_start_requests_valid_lifecycle_state')),
    sa.CheckConstraint("\n            idempotency_key_hash\n            ~ '^[0-9a-f]{64}$'\n            ", name=op.f('ck_conversation_start_requests_valid_idempotency_key_hash')),
    sa.CheckConstraint("\n            request_fingerprint\n            ~ '^[0-9a-f]{64}$'\n            ", name=op.f('ck_conversation_start_requests_valid_request_fingerprint')),
    sa.CheckConstraint("\n            response_snapshot IS NULL\n            OR jsonb_typeof(response_snapshot) = 'object'\n            ", name=op.f('ck_conversation_start_requests_response_snapshot_is_object')),
    sa.CheckConstraint("\n            status IN (\n                'accepted',\n                'processing',\n                'completed',\n                'failed'\n            )\n            ", name=op.f('ck_conversation_start_requests_valid_status')),
    sa.CheckConstraint('\n            completed_at IS NULL\n            OR completed_at >= created_at\n            ', name=op.f('ck_conversation_start_requests_valid_completion_timestamp')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_conversation_start_requests_nonnegative_attempt_count')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_conversation_start_requests_valid_expiration')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_conversation_start_requests_valid_timestamp_order')),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_conversation_start_requests_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['support.users.id'], name=op.f('fk_conversation_start_requests_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_message_id'], ['support.messages.id'], name=op.f('fk_conversation_start_requests_customer_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_ai_run_id'], ['ai.runs.id'], name=op.f('fk_conversation_start_requests_latest_ai_run_id_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_start_requests')),
    sa.UniqueConstraint('customer_id', 'idempotency_key_hash', name='uq_conversation_start_requests_customer_key'),
    schema='support'
    )
    op.create_index('idx_conversation_start_requests_conversation', 'conversation_start_requests', ['conversation_id'], unique=False, schema='support')
    op.create_index('idx_conversation_start_requests_expires_at', 'conversation_start_requests', ['expires_at'], unique=False, schema='support')
    op.create_index('idx_conversation_start_requests_status_lease', 'conversation_start_requests', ['status', 'processing_expires_at'], unique=False, schema='support')
    op.execute(
        """
        UPDATE support.escalations
        SET reason_code = lower(reason_code)
        WHERE reason_code <> lower(reason_code)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_start_requests_status_lease', table_name='conversation_start_requests', schema='support')
    op.drop_index('idx_conversation_start_requests_expires_at', table_name='conversation_start_requests', schema='support')
    op.drop_index('idx_conversation_start_requests_conversation', table_name='conversation_start_requests', schema='support')
    op.drop_table('conversation_start_requests', schema='support')
    # ### end Alembic commands ###
