"""create authentication credentials and sessions

Revision ID: 34f75d0825a5
Revises: fc9f99c38a15
Create Date: 2026-09-11 19:51:12.350715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f75d0825a5'
down_revision: Union[str, Sequence[str], None] = 'fc9f99c38a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.Column('client_ip', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=100), nullable=True),
    sa.CheckConstraint('\n            (revoked_at IS NULL AND revocation_reason IS NULL)\n            OR\n            (revoked_at IS NOT NULL)\n            ', name=op.f('ck_auth_sessions_valid_revocation_state')),
    sa.CheckConstraint('\n            replaced_by_session_id IS NULL\n            OR revoked_at IS NOT NULL\n            ', name=op.f('ck_auth_sessions_replacement_requires_revocation')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_auth_sessions_expires_after_creation')),
    sa.CheckConstraint('length(btrim(refresh_token_hash)) > 0', name=op.f('ck_auth_sessions_refresh_token_hash_not_blank')),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['support.auth_sessions.id'], name=op.f('fk_auth_sessions_replaced_by_session_id_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['support.users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash')),
    sa.UniqueConstraint('replaced_by_session_id', name=op.f('uq_auth_sessions_replaced_by_session_id')),
    schema='support'
    )
    op.create_index('idx_auth_sessions_active_user', 'auth_sessions', ['user_id', 'expires_at'], unique=False, schema='support', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_auth_sessions_expires', 'auth_sessions', ['expires_at'], unique=False, schema='support')
    op.create_index('idx_auth_sessions_family', 'auth_sessions', ['family_id'], unique=False, schema='support')
    op.create_index('idx_auth_sessions_user_created', 'auth_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_table('user_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email_normalized = lower(btrim(email_normalized))', name=op.f('ck_user_credentials_email_is_normalized')),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_user_credentials_failed_login_attempts_non_negative')),
    sa.CheckConstraint('length(btrim(email_normalized)) > 0', name=op.f('ck_user_credentials_email_not_blank')),
    sa.CheckConstraint('length(btrim(password_hash)) > 0', name=op.f('ck_user_credentials_password_hash_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['support.users.id'], name=op.f('fk_user_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_credentials')),
    sa.UniqueConstraint('email_normalized', name=op.f('uq_user_credentials_email_normalized')),
    schema='support'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials', schema='support')
    op.drop_index('idx_auth_sessions_user_created', table_name='auth_sessions', schema='support')
    op.drop_index('idx_auth_sessions_family', table_name='auth_sessions', schema='support')
    op.drop_index('idx_auth_sessions_expires', table_name='auth_sessions', schema='support')
    op.drop_index('idx_auth_sessions_active_user', table_name='auth_sessions', schema='support', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('auth_sessions', schema='support')
    # ### end Alembic commands ###
