"""create audit api requests

Revision ID: 47319e30c4e6
Revises: 8dd0b7d36a55
Create Date: 2026-09-08 02:43:36.850185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47319e30c4e6'
down_revision: Union[str, Sequence[str], None] = '8dd0b7d36a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('route_template', sa.String(length=500), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('request_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('response_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                outcome = 'success'\n                AND status_code < 400\n                AND error_code IS NULL\n            )\n            OR\n            (\n                outcome = 'client_error'\n                AND status_code BETWEEN 400 AND 499\n            )\n            OR\n            (\n                outcome = 'server_error'\n                AND status_code >= 500\n            )\n            ", name=op.f('ck_api_requests_valid_outcome_status')),
    sa.CheckConstraint("\n            method IN (\n                'GET',\n                'POST',\n                'PUT',\n                'PATCH',\n                'DELETE',\n                'OPTIONS',\n                'HEAD'\n            )\n            ", name=op.f('ck_api_requests_valid_method')),
    sa.CheckConstraint("\n            outcome IN (\n                'success',\n                'client_error',\n                'server_error'\n            )\n            ", name=op.f('ck_api_requests_valid_outcome')),
    sa.CheckConstraint('\n            request_size_bytes IS NULL\n            OR request_size_bytes >= 0\n            ', name=op.f('ck_api_requests_non_negative_request_size')),
    sa.CheckConstraint('\n            response_size_bytes IS NULL\n            OR response_size_bytes >= 0\n            ', name=op.f('ck_api_requests_non_negative_response_size')),
    sa.CheckConstraint('completed_at >= started_at', name=op.f('ck_api_requests_valid_completion_time')),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('ck_api_requests_non_negative_latency')),
    sa.CheckConstraint('status_code BETWEEN 100 AND 599', name=op.f('ck_api_requests_valid_status_code')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['support.users.id'], name=op.f('fk_api_requests_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_requests')),
    schema='audit'
    )
    op.create_index('idx_api_requests_actor_started', 'api_requests', ['actor_user_id', sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_error_started', 'api_requests', ['error_code', sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_latency', 'api_requests', [sa.literal_column('latency_ms DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_outcome_started', 'api_requests', ['outcome', sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_route_started', 'api_requests', ['route_template', sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_started', 'api_requests', [sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_status_started', 'api_requests', ['status_code', sa.literal_column('started_at DESC')], unique=False, schema='audit')
    op.create_index('idx_api_requests_trace', 'api_requests', ['trace_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_requests_trace', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_status_started', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_started', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_route_started', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_outcome_started', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_latency', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_error_started', table_name='api_requests', schema='audit')
    op.drop_index('idx_api_requests_actor_started', table_name='api_requests', schema='audit')
    op.drop_table('api_requests', schema='audit')
    # ### end Alembic commands ###
