"""create support escalations

Revision ID: 5d33f08b47ea
Revises: bd4544c193d6
Create Date: 2026-09-06 20:55:38.435024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d33f08b47ea'
down_revision: Union[str, Sequence[str], None] = 'bd4544c193d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('trigger_message_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('handoff_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status IN ('resolved', 'dismissed')\n                AND resolved_at IS NOT NULL\n            )\n            OR\n            (\n                status IN ('open', 'in_review')\n                AND resolved_at IS NULL\n            )\n            ", name=op.f('ck_escalations_valid_resolution_state')),
    sa.CheckConstraint("\n            priority IN ('low', 'normal', 'high', 'urgent')\n            ", name=op.f('ck_escalations_valid_priority')),
    sa.CheckConstraint("\n            source IN ('decision', 'guardrail', 'system', 'manual')\n            ", name=op.f('ck_escalations_valid_source')),
    sa.CheckConstraint("\n            status IN ('open', 'in_review', 'resolved', 'dismissed')\n            ", name=op.f('ck_escalations_valid_status')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_escalations_ai_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_escalations_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['support.messages.id'], name=op.f('fk_escalations_trigger_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations')),
    schema='support'
    )
    op.create_index("uq_escalations_ai_run", "escalations", ["ai_run_id"], unique=True, schema="support", postgresql_where=sa.text("ai_run_id IS NOT NULL"))
    op.create_index('idx_escalations_conversation_created', 'escalations', ['conversation_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_escalations_priority_status', 'escalations', ['priority', 'status'], unique=False, schema='support')
    op.create_index('idx_escalations_reason_code', 'escalations', ['reason_code'], unique=False, schema='support')
    op.create_index('idx_escalations_status_created', 'escalations', ['status', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_escalations_trigger_message', 'escalations', ['trigger_message_id'], unique=False, schema='support')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_escalations_trigger_message', table_name='escalations', schema='support')
    op.drop_index('idx_escalations_status_created', table_name='escalations', schema='support')
    op.drop_index('idx_escalations_reason_code', table_name='escalations', schema='support')
    op.drop_index('idx_escalations_priority_status', table_name='escalations', schema='support')
    op.drop_index('idx_escalations_conversation_created', table_name='escalations', schema='support')
    op.drop_index("uq_escalations_ai_run", table_name="escalations", schema="support")
    op.drop_table('escalations', schema='support')
    # ### end Alembic commands ###
