"""add dashboard analytics timestamp indexes

Revision ID: 61d9a8f61a00
Revises: a37987efa2e6
Create Date: 2026-09-15 12:51:02.448393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d9a8f61a00'
down_revision: Union[str, Sequence[str], None] = 'a37987efa2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ai_decisions_created_at', 'decisions', ['created_at'], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_started_at', 'embedding_calls', ['started_at'], unique=False, schema='ai')
    op.create_index('idx_intent_predictions_created_at', 'intent_predictions', ['created_at'], unique=False, schema='ai')
    op.create_index('idx_llm_calls_started_at', 'llm_calls', ['started_at'], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_started_at', 'reranker_calls', ['started_at'], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_started_at', 'retrieval_runs', ['started_at'], unique=False, schema='ai')
    op.create_index('idx_ai_runs_started_at', 'runs', ['started_at'], unique=False, schema='ai')
    op.create_index('ix_knowledge_document_versions_created_at', 'knowledge_document_versions', ['created_at'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_document_versions_processing_completed_at', 'knowledge_document_versions', ['processing_completed_at'], unique=False, schema='knowledge', postgresql_where=sa.text('processing_completed_at IS NOT NULL'))
    op.create_index('idx_conversations_closed_at', 'conversations', ['closed_at'], unique=False, schema='support', postgresql_where=sa.text('closed_at IS NOT NULL'))
    op.create_index('idx_conversations_created_at', 'conversations', ['created_at'], unique=False, schema='support')
    op.create_index('idx_escalations_created_at', 'escalations', ['created_at'], unique=False, schema='support')
    op.create_index('idx_escalations_resolved_at', 'escalations', ['resolved_at'], unique=False, schema='support', postgresql_where=sa.text('resolved_at IS NOT NULL'))
    op.create_index('idx_feedback_created_at', 'feedback', ['created_at'], unique=False, schema='support')
    op.create_index('idx_messages_created_at', 'messages', ['created_at'], unique=False, schema='support')
    op.create_index('idx_tickets_closed_at', 'tickets', ['closed_at'], unique=False, schema='support', postgresql_where=sa.text('closed_at IS NOT NULL'))
    op.create_index('idx_tickets_created_at', 'tickets', ['created_at'], unique=False, schema='support')
    op.create_index('idx_tickets_resolved_at', 'tickets', ['resolved_at'], unique=False, schema='support', postgresql_where=sa.text('resolved_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_resolved_at', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_created_at', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_closed_at', table_name='tickets', schema='support')
    op.drop_index('idx_messages_created_at', table_name='messages', schema='support')
    op.drop_index('idx_feedback_created_at', table_name='feedback', schema='support')
    op.drop_index('idx_escalations_resolved_at', table_name='escalations', schema='support')
    op.drop_index('idx_escalations_created_at', table_name='escalations', schema='support')
    op.drop_index('idx_conversations_created_at', table_name='conversations', schema='support')
    op.drop_index('idx_conversations_closed_at', table_name='conversations', schema='support')
    op.drop_index('ix_knowledge_document_versions_processing_completed_at', table_name='knowledge_document_versions', schema='knowledge')
    op.drop_index('ix_knowledge_document_versions_created_at', table_name='knowledge_document_versions', schema='knowledge')
    op.drop_index('idx_ai_runs_started_at', table_name='runs', schema='ai')
    op.drop_index('idx_retrieval_runs_started_at', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_reranker_calls_started_at', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_llm_calls_started_at', table_name='llm_calls', schema='ai')
    op.drop_index('idx_intent_predictions_created_at', table_name='intent_predictions', schema='ai')
    op.drop_index('idx_embedding_calls_started_at', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_ai_decisions_created_at', table_name='decisions', schema='ai')
    # ### end Alembic commands ###
