"""create support core tables

Revision ID: 88b04a494d31
Revises: 
Create Date: 2026-08-26 00:29:42.852251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88b04a494d31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'support_agent', 'admin', 'system')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint("status IN ('active', 'disabled', 'deleted')", name=op.f('ck_users_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('external_id', name=op.f('uq_users_external_id')),
    schema='support'
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            status IN (\n                'open',\n                'waiting_for_customer',\n                'waiting_for_agent',\n                'escalated',\n                'resolved',\n                'closed'\n            )\n            ", name=op.f('ck_conversations_valid_status')),
    sa.CheckConstraint("channel IN ('web', 'mobile', 'email', 'api')", name=op.f('ck_conversations_valid_channel')),
    sa.ForeignKeyConstraint(['user_id'], ['support.users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    schema='support'
    )
    op.create_index('idx_conversations_user_created_at', 'conversations', ['user_id', 'created_at'], unique=False, schema='support')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            role IN (\n                'customer',\n                'assistant',\n                'support_agent',\n                'system',\n                'tool'\n            )\n            ", name=op.f('ck_messages_valid_role')),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'sequence_number', name='uq_messages_conversation_sequence'),
    schema='support'
    )
    op.create_index('idx_messages_conversation_sequence', 'messages', ['conversation_id', 'sequence_number'], unique=False, schema='support')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_conversation_sequence', table_name='messages', schema='support')
    op.drop_table('messages', schema='support')
    op.drop_index('idx_conversations_user_created_at', table_name='conversations', schema='support')
    op.drop_table('conversations', schema='support')
    op.drop_table('users', schema='support')
    # ### end Alembic commands ###
