"""create feedback properly

Revision ID: 8dd0b7d36a55
Revises: 9a87bb2fde45
Create Date: 2026-09-07 18:23:07.320233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd0b7d36a55'
down_revision: Union[str, Sequence[str], None] = '9a87bb2fde45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('response_message_id', sa.UUID(), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'pending'\n                AND reviewed_at IS NULL\n                AND reviewed_by_user_id IS NULL\n                AND review_notes IS NULL\n            )\n            OR\n            (\n                status IN ('reviewed', 'actioned', 'dismissed')\n                AND reviewed_at IS NOT NULL\n            )\n            ", name=op.f('ck_feedback_valid_review_state')),
    sa.CheckConstraint("\n            status IN (\n                'pending',\n                'reviewed',\n                'actioned',\n                'dismissed'\n            )\n            ", name=op.f('ck_feedback_valid_status')),
    sa.CheckConstraint('\n            comment IS NULL\n            OR length(btrim(comment)) > 0\n            ', name=op.f('ck_feedback_comment_not_blank')),
    sa.CheckConstraint('\n            review_notes IS NULL\n            OR length(btrim(review_notes)) > 0\n            ', name=op.f('ck_feedback_review_notes_not_blank')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_feedback_valid_rating')),
    sa.CheckConstraint('row_version > 0', name=op.f('ck_feedback_positive_row_version')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_feedback_valid_updated_at')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_feedback_ai_run_id_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_feedback_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['support.users.id'], name=op.f('fk_feedback_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['response_message_id'], ['support.messages.id'], name=op.f('fk_feedback_response_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['support.users.id'], name=op.f('fk_feedback_reviewed_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('response_message_id', name='uq_feedback_response_message'),
    schema='support'
    )
    op.create_index('idx_feedback_ai_run', 'feedback', ['ai_run_id'], unique=False, schema='support')
    op.create_index('idx_feedback_conversation_created', 'feedback', ['conversation_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_feedback_customer_created', 'feedback', ['customer_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_feedback_helpful_created', 'feedback', ['helpful', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_feedback_rating_created', 'feedback', ['rating', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_feedback_status_created', 'feedback', ['status', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index("idx_feedback_reason_codes_gin", "feedback", ["reason_codes"], unique=False, schema="support", postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_feedback_reason_codes_gin", table_name="feedback", schema="support", postgresql_using="gin")
    op.drop_index('idx_feedback_status_created', table_name='feedback', schema='support')
    op.drop_index('idx_feedback_rating_created', table_name='feedback', schema='support')
    op.drop_index('idx_feedback_helpful_created', table_name='feedback', schema='support')
    op.drop_index('idx_feedback_customer_created', table_name='feedback', schema='support')
    op.drop_index('idx_feedback_conversation_created', table_name='feedback', schema='support')
    op.drop_index('idx_feedback_ai_run', table_name='feedback', schema='support')
    op.drop_table('feedback', schema='support')
    # ### end Alembic commands ###
