"""create support tickets

Revision ID: 9a87bb2fde45
Revises: 5d33f08b47ea
Create Date: 2026-09-06 23:37:04.544497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a87bb2fde45'
down_revision: Union[str, Sequence[str], None] = '5d33f08b47ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ticket_number', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('escalation_id', sa.UUID(), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='general', nullable=False),
    sa.Column('priority', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'closed'\n                AND closed_at IS NOT NULL\n            )\n            OR\n            (\n                status <> 'closed'\n                AND closed_at IS NULL\n            )\n            ", name=op.f('ck_tickets_valid_closed_state')),
    sa.CheckConstraint("\n            (\n                status IN ('resolved', 'closed')\n                AND resolved_at IS NOT NULL\n                AND resolution_summary IS NOT NULL\n            )\n            OR\n            (\n                status NOT IN ('resolved', 'closed')\n                AND resolved_at IS NULL\n                AND resolution_summary IS NULL\n            )\n            ", name=op.f('ck_tickets_valid_resolution_state')),
    sa.CheckConstraint("\n            category IN (\n                'billing',\n                'refund',\n                'order',\n                'account',\n                'technical',\n                'security',\n                'product',\n                'general',\n                'other'\n            )\n            ", name=op.f('ck_tickets_valid_category')),
    sa.CheckConstraint("\n            priority IN (\n                'low',\n                'normal',\n                'high',\n                'urgent'\n            )\n            ", name=op.f('ck_tickets_valid_priority')),
    sa.CheckConstraint("\n            source IN (\n                'customer',\n                'escalation',\n                'agent',\n                'system'\n            )\n            ", name=op.f('ck_tickets_valid_source')),
    sa.CheckConstraint("\n            status IN (\n                'open',\n                'in_progress',\n                'waiting_for_customer',\n                'resolved',\n                'closed',\n                'reopened'\n            )\n            ", name=op.f('ck_tickets_valid_status')),
    sa.CheckConstraint('\n            assigned_agent_id IS NULL\n            OR assigned_at IS NOT NULL\n            ', name=op.f('ck_tickets_valid_assignment_state')),
    sa.CheckConstraint('\n            assigned_at IS NULL\n            OR assigned_at >= created_at\n            ', name=op.f('ck_tickets_valid_assigned_at')),
    sa.CheckConstraint('\n            closed_at IS NULL\n            OR closed_at >= created_at\n            ', name=op.f('ck_tickets_valid_closed_at')),
    sa.CheckConstraint('\n            resolution_summary IS NULL\n            OR length(btrim(resolution_summary)) > 0\n            ', name=op.f('ck_tickets_resolution_summary_not_blank')),
    sa.CheckConstraint('\n            resolved_at IS NULL\n            OR resolved_at >= created_at\n            ', name=op.f('ck_tickets_valid_resolved_at')),
    sa.CheckConstraint('length(btrim(description)) > 0', name=op.f('ck_tickets_description_not_blank')),
    sa.CheckConstraint('length(btrim(subject)) > 0', name=op.f('ck_tickets_subject_not_blank')),
    sa.CheckConstraint('row_version > 0', name=op.f('ck_tickets_positive_row_version')),
    sa.CheckConstraint('updated_at >= created_at', name=op.f('ck_tickets_valid_updated_at')),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['support.users.id'], name=op.f('fk_tickets_assigned_agent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_tickets_conversation_id_conversations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['support.users.id'], name=op.f('fk_tickets_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['escalation_id'], ['support.escalations.id'], name=op.f('fk_tickets_escalation_id_escalations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['support.messages.id'], name=op.f('fk_tickets_source_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('ticket_number', name='uq_tickets_ticket_number'),
    schema='support'
    )
    op.create_index('idx_tickets_assignee_status', 'tickets', ['assigned_agent_id', 'status'], unique=False, schema='support')
    op.create_index('idx_tickets_category_created', 'tickets', ['category', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_tickets_conversation_created', 'tickets', ['conversation_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_tickets_customer_created', 'tickets', ['customer_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_tickets_priority_status', 'tickets', ['priority', 'status'], unique=False, schema='support')
    op.create_index('idx_tickets_status_created', 'tickets', ['status', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('uq_tickets_escalation', 'tickets', ['escalation_id'], unique=True, schema='support', postgresql_where=sa.text('escalation_id IS NOT NULL'))
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_role', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='customer', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            author_role <> 'customer'\n            OR visibility = 'customer'\n            ", name=op.f('ck_ticket_comments_customer_comment_visibility')),
    sa.CheckConstraint("\n            author_role IN (\n                'customer',\n                'support_agent',\n                'admin',\n                'system'\n            )\n            ", name=op.f('ck_ticket_comments_valid_author_role')),
    sa.CheckConstraint("\n            visibility IN (\n                'customer',\n                'internal'\n            )\n            ", name=op.f('ck_ticket_comments_valid_visibility')),
    sa.CheckConstraint('length(btrim(content)) > 0', name=op.f('ck_ticket_comments_content_not_blank')),
    sa.ForeignKeyConstraint(['author_id'], ['support.users.id'], name=op.f('fk_ticket_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support.tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments')),
    schema='support'
    )
    op.create_index('idx_ticket_comments_author_created', 'ticket_comments', ['author_id', sa.literal_column('created_at DESC')], unique=False, schema='support')
    op.create_index('idx_ticket_comments_ticket_created', 'ticket_comments', ['ticket_id', 'created_at', 'id'], unique=False, schema='support')
    op.create_index('idx_ticket_comments_visibility_created', 'ticket_comments', ['visibility', sa.literal_column('created_at DESC')], unique=False, schema='support')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ticket_comments_visibility_created', table_name='ticket_comments', schema='support')
    op.drop_index('idx_ticket_comments_ticket_created', table_name='ticket_comments', schema='support')
    op.drop_index('idx_ticket_comments_author_created', table_name='ticket_comments', schema='support')
    op.drop_table('ticket_comments', schema='support')
    op.drop_index('uq_tickets_escalation', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_status_created', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_priority_status', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_customer_created', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_conversation_created', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_category_created', table_name='tickets', schema='support')
    op.drop_index('idx_tickets_assignee_status', table_name='tickets', schema='support')
    op.drop_table('tickets', schema='support')
    # ### end Alembic commands ###
