"""add knowledge version content hash lookup index

Revision ID: a37987efa2e6
Revises: 34f75d0825a5
Create Date: 2026-09-14 14:41:33.403928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37987efa2e6'
down_revision: Union[str, Sequence[str], None] = '34f75d0825a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_document_versions_document_content_hash', 'knowledge_document_versions', ['document_id', 'source_type', 'content_hash'], unique=False, schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_document_versions_document_content_hash', table_name='knowledge_document_versions', schema='knowledge')
    # ### end Alembic commands ###
