"""add conversation message sequence counter

Revision ID: b90f79768b86
Revises: df642c5b32e8
Create Date: 2026-08-26 18:54:12.402047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90f79768b86'
down_revision: Union[str, Sequence[str], None] = 'df642c5b32e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('next_message_sequence', sa.BigInteger(), server_default='1', nullable=False), schema='support')
    op.create_check_constraint(op.f('ck_conversations_valid_next_message_sequence'), 'conversations', 'next_message_sequence >= 1', schema='support')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_conversations_valid_next_message_sequence'), 'conversations', schema='support', type_='check')
    op.drop_column('conversations', 'next_message_sequence', schema='support')
    # ### end Alembic commands ###
