"""add knowledge chunk embeddings

Revision ID: bd4544c193d6
Revises: de48e87a85a0
Create Date: 2026-09-01 13:46:50.717619

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4544c193d6'
down_revision: Union[str, Sequence[str], None] = 'de48e87a85a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('knowledge_chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('input_strategy_id', sa.String(length=100), nullable=False),
    sa.Column('input_strategy_version', sa.String(length=100), nullable=False),
    sa.Column('input_config_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dimensions > 0', name=op.f('ck_knowledge_chunk_embeddings_dimensions_positive')),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge.knowledge_chunks.id'], name=op.f('fk_knowledge_chunk_embeddings_chunk_id_knowledge_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunk_embeddings')),
    sa.UniqueConstraint('chunk_id', 'provider', 'model', 'model_revision', 'dimensions', 'input_strategy_id', 'input_strategy_version', 'input_config_fingerprint', 'input_fingerprint', name='uq_knowledge_chunk_embeddings_artifact', postgresql_nulls_not_distinct=True),
    schema='knowledge'
    )
    op.create_index('ix_knowledge_chunk_embeddings_chunk_id', 'knowledge_chunk_embeddings', ['chunk_id'], unique=False, schema='knowledge')
    op.create_index('ix_knowledge_chunk_embeddings_provider_model_dimensions', 'knowledge_chunk_embeddings', ['provider', 'model', 'dimensions'], unique=False, schema='knowledge')
    op.drop_index(op.f('uq_knowledge_document_versions_one_published'), table_name='knowledge_document_versions', schema='knowledge', postgresql_where="((status)::text = 'published'::text)")
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_027a'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_2b77'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_37cb'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_6738'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_9acc'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_b7ae'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_bd1b'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_content_not_blank'), 'knowledge_document_versions', 'length(btrim(source_content)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_hash_not_blank'), 'knowledge_document_versions', 'length(btrim(content_hash)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_ingestion_status'), 'knowledge_document_versions', "ingestion_status IN ('pending', 'running', 'completed', 'failed')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_positive_version'), 'knowledge_document_versions', 'version_number > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_source_type'), 'knowledge_document_versions', "source_type IN ('markdown', 'plain_text', 'pdf', 'docx', 'html', 'rich_text')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_status'), 'knowledge_document_versions', "status IN ('draft', 'processing', 'ready', 'published', 'superseded', 'failed', 'archived')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_timestamp_order'), 'knowledge_document_versions', 'updated_at >= created_at', schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_timestamp_order'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_status'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_source_type'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_positive_version'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_ingestion_status'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_hash_not_blank'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_versions_content_not_blank'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_bd1b'), 'knowledge_document_versions', "status::text = ANY (ARRAY['draft'::character varying, 'processing'::character varying, 'ready'::character varying, 'published'::character varying, 'superseded'::character varying, 'failed'::character varying, 'archived'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_b7ae'), 'knowledge_document_versions', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_9acc'), 'knowledge_document_versions', 'version_number > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_6738'), 'knowledge_document_versions', "ingestion_status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_37cb'), 'knowledge_document_versions', 'length(btrim(content_hash::text)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_2b77'), 'knowledge_document_versions', 'length(btrim(source_content)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_027a'), 'knowledge_document_versions', "source_type::text = ANY (ARRAY['markdown'::character varying, 'plain_text'::character varying, 'pdf'::character varying, 'docx'::character varying, 'html'::character varying, 'rich_text'::character varying]::text[])", schema='knowledge')
    op.create_index(op.f('uq_knowledge_document_versions_one_published'), 'knowledge_document_versions', ['document_id'], unique=True, schema='knowledge', postgresql_where="((status)::text = 'published'::text)")
    op.drop_index('ix_knowledge_chunk_embeddings_provider_model_dimensions', table_name='knowledge_chunk_embeddings', schema='knowledge')
    op.drop_index('ix_knowledge_chunk_embeddings_chunk_id', table_name='knowledge_chunk_embeddings', schema='knowledge')
    op.drop_table('knowledge_chunk_embeddings', schema='knowledge')
    # ### end Alembic commands ###
