"""create immutable business audit events

Revision ID: c2e74a42d07e
Revises: 47319e30c4e6
Create Date: 2026-09-08 04:45:28.427036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e74a42d07e'
down_revision: Union[str, Sequence[str], None] = '47319e30c4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                actor_type IN ('system', 'ai')\n                AND actor_id IS NULL\n            )\n            OR\n            actor_type IN ('customer', 'agent', 'admin')\n            ", name=op.f('ck_audit_events_valid_actor_identity')),
    sa.CheckConstraint("\n            actor_type IN (\n                'customer',\n                'agent',\n                'admin',\n                'system',\n                'ai'\n            )\n            ", name=op.f('ck_audit_events_valid_actor_type')),
    sa.CheckConstraint('length(trim(action)) > 0', name=op.f('ck_audit_events_non_empty_action')),
    sa.CheckConstraint('length(trim(entity_type)) > 0', name=op.f('ck_audit_events_non_empty_entity_type')),
    sa.CheckConstraint('length(trim(event_type)) > 0', name=op.f('ck_audit_events_non_empty_event_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    schema='audit'
    )
    op.create_index('idx_audit_events_actor_occurred', 'audit_events', ['actor_type', 'actor_id', sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_ai_run', 'audit_events', ['ai_run_id', sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_conversation', 'audit_events', ['conversation_id', sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_entity_occurred', 'audit_events', ['entity_type', 'entity_id', sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_event_occurred', 'audit_events', ['event_type', sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_occurred', 'audit_events', [sa.literal_column('occurred_at DESC')], unique=False, schema='audit')
    op.create_index('idx_audit_events_trace', 'audit_events', ['trace_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_events_trace', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_occurred', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_event_occurred', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_entity_occurred', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_conversation', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_ai_run', table_name='audit_events', schema='audit')
    op.drop_index('idx_audit_events_actor_occurred', table_name='audit_events', schema='audit')
    op.drop_table('audit_events', schema='audit')
    # ### end Alembic commands ###
