"""add ai execution observability 2

Revision ID: df642c5b32e8
Revises: 88b04a494d31
Create Date: 2026-08-26 01:40:59.313804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df642c5b32e8'
down_revision: Union[str, Sequence[str], None] = '88b04a494d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'retired')", name=op.f('ck_prompt_versions_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('prompt_name', 'version', name='uq_prompt_name_version'),
    schema='config'
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_message_id', sa.UUID(), nullable=False),
    sa.Column('response_message_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'cancelled')", name=op.f('ck_runs_valid_status')),
    sa.CheckConstraint('total_latency_ms IS NULL OR total_latency_ms >= 0', name=op.f('ck_runs_valid_total_latency')),
    sa.ForeignKeyConstraint(['conversation_id'], ['support.conversations.id'], name=op.f('fk_runs_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['parent_run_id'], ['ai.runs.id'], name=op.f('fk_runs_parent_run_id_runs')),
    sa.ForeignKeyConstraint(['response_message_id'], ['support.messages.id'], name=op.f('fk_runs_response_message_id_messages')),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['support.messages.id'], name=op.f('fk_runs_trigger_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    schema='ai'
    )
    op.create_index('idx_ai_runs_conversation_started', 'runs', ['conversation_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_ai_runs_parent', 'runs', ['parent_run_id'], unique=False, schema='ai')
    op.create_index('idx_ai_runs_status_started', 'runs', ['status', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_ai_runs_trace', 'runs', ['trace_id'], unique=False, schema='ai')
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            purpose IN (\n                'intent_classification',\n                'query_rewrite',\n                'answer_generation',\n                'action_decision',\n                'escalation_summary',\n                'guardrail_validation',\n                'conversation_summary',\n                'other'\n            )\n            ", name=op.f('ck_llm_calls_valid_purpose')),
    sa.CheckConstraint("status IN ('success', 'failed', 'timeout')", name=op.f('ck_llm_calls_valid_status')),
    sa.CheckConstraint('cached_input_tokens >= 0', name=op.f('ck_llm_calls_valid_cached_input_tokens')),
    sa.CheckConstraint('estimated_cost_usd IS NULL OR estimated_cost_usd >= 0', name=op.f('ck_llm_calls_valid_estimated_cost')),
    sa.CheckConstraint('input_tokens >= 0', name=op.f('ck_llm_calls_valid_input_tokens')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_llm_calls_valid_latency')),
    sa.CheckConstraint('output_tokens >= 0', name=op.f('ck_llm_calls_valid_output_tokens')),
    sa.CheckConstraint('temperature IS NULL OR (temperature >= 0 AND temperature <= 2)', name=op.f('ck_llm_calls_valid_temperature')),
    sa.CheckConstraint('total_tokens >= 0', name=op.f('ck_llm_calls_valid_total_tokens')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_llm_calls_ai_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['config.prompt_versions.id'], name=op.f('fk_llm_calls_prompt_version_id_prompt_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls')),
    schema='ai'
    )
    op.create_index('idx_llm_calls_ai_run', 'llm_calls', ['ai_run_id'], unique=False, schema='ai')
    op.create_index('idx_llm_calls_model_started', 'llm_calls', ['provider', 'model', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_llm_calls_purpose_started', 'llm_calls', ['purpose', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_llm_calls_status_started', 'llm_calls', ['status', 'started_at'], unique=False, schema='ai')
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=False),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            decision_type IN (\n                'answer',\n                'retrieve_information',\n                'perform_action',\n                'ask_clarification',\n                'escalate'\n            )\n            ", name=op.f('ck_decisions_valid_decision_type')),
    sa.CheckConstraint('\n            confidence IS NULL\n            OR (confidence >= 0 AND confidence <= 1)\n            ', name=op.f('ck_decisions_valid_confidence')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_decisions_ai_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['ai.llm_calls.id'], name=op.f('fk_decisions_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions')),
    schema='ai'
    )
    op.create_index('idx_ai_decisions_llm_call', 'decisions', ['llm_call_id'], unique=False, schema='ai')
    op.create_index('idx_ai_decisions_reason_code', 'decisions', ['reason_code'], unique=False, schema='ai')
    op.create_index('idx_ai_decisions_run', 'decisions', ['ai_run_id'], unique=False, schema='ai')
    op.create_index('idx_ai_decisions_type_created', 'decisions', ['decision_type', sa.literal_column('created_at DESC')], unique=False, schema='ai')
    op.create_table('intent_predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=False),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('needs_clarification', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            confidence IS NULL\n            OR (confidence >= 0 AND confidence <= 1)\n            ', name=op.f('ck_intent_predictions_valid_confidence')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_intent_predictions_ai_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['ai.llm_calls.id'], name=op.f('fk_intent_predictions_llm_call_id_llm_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intent_predictions')),
    schema='ai'
    )
    op.create_index('idx_intent_predictions_ai_run', 'intent_predictions', ['ai_run_id'], unique=False, schema='ai')
    op.create_index('idx_intent_predictions_confidence', 'intent_predictions', ['confidence'], unique=False, schema='ai')
    op.create_index('idx_intent_predictions_intent_created', 'intent_predictions', ['intent', 'created_at'], unique=False, schema='ai')
    op.create_index('idx_intent_predictions_llm_call', 'intent_predictions', ['llm_call_id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intent_predictions_llm_call', table_name='intent_predictions', schema='ai')
    op.drop_index('idx_intent_predictions_intent_created', table_name='intent_predictions', schema='ai')
    op.drop_index('idx_intent_predictions_confidence', table_name='intent_predictions', schema='ai')
    op.drop_index('idx_intent_predictions_ai_run', table_name='intent_predictions', schema='ai')
    op.drop_table('intent_predictions', schema='ai')
    op.drop_index('idx_ai_decisions_type_created', table_name='decisions', schema='ai')
    op.drop_index('idx_ai_decisions_run', table_name='decisions', schema='ai')
    op.drop_index('idx_ai_decisions_reason_code', table_name='decisions', schema='ai')
    op.drop_index('idx_ai_decisions_llm_call', table_name='decisions', schema='ai')
    op.drop_table('decisions', schema='ai')
    op.drop_index('idx_llm_calls_status_started', table_name='llm_calls', schema='ai')
    op.drop_index('idx_llm_calls_purpose_started', table_name='llm_calls', schema='ai')
    op.drop_index('idx_llm_calls_model_started', table_name='llm_calls', schema='ai')
    op.drop_index('idx_llm_calls_ai_run', table_name='llm_calls', schema='ai')
    op.drop_table('llm_calls', schema='ai')
    op.drop_index('idx_ai_runs_trace', table_name='runs', schema='ai')
    op.drop_index('idx_ai_runs_status_started', table_name='runs', schema='ai')
    op.drop_index('idx_ai_runs_parent', table_name='runs', schema='ai')
    op.drop_index('idx_ai_runs_conversation_started', table_name='runs', schema='ai')
    op.drop_table('runs', schema='ai')
    op.drop_table('prompt_versions', schema='config')
    # ### end Alembic commands ###
