"""add intent escalation signals

Revision ID: e276f083ae3c
Revises: 61d9a8f61a00
Create Date: 2026-09-17 15:34:59.507138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e276f083ae3c'
down_revision: Union[str, Sequence[str], None] = '61d9a8f61a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_predictions', sa.Column('escalation_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False), schema='ai')
    op.create_index('idx_intent_predictions_escalation_signals', 'intent_predictions', ['escalation_signals'], unique=False, schema='ai', postgresql_using='gin')
    op.create_check_constraint(op.f('ck_intent_predictions_valid_escalation_signals'), 'intent_predictions', '\n            jsonb_typeof(escalation_signals) = \'array\'\n            AND escalation_signals\n                <@ \'[\n                    "explicit_human_request",\n                    "severe_customer_dissatisfaction"\n                ]\'::jsonb\n            ', schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_intent_predictions_valid_escalation_signals'), 'intent_predictions', schema='ai', type_='check')
    op.drop_index('idx_intent_predictions_escalation_signals', table_name='intent_predictions', schema='ai', postgresql_using='gin')
    op.drop_column('intent_predictions', 'escalation_signals', schema='ai')
    # ### end Alembic commands ###
