"""create AI telemetry tables

Revision ID: fc9f99c38a15
Revises: c2e74a42d07e
Create Date: 2026-09-08 22:47:05.155030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc9f99c38a15'
down_revision: Union[str, Sequence[str], None] = 'c2e74a42d07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_version_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('provider_revision', sa.String(length=200), nullable=True),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('total_input_characters', sa.Integer(), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'started'\n                AND completed_at IS NULL\n                AND latency_ms IS NULL\n                AND error_code IS NULL\n            )\n            OR\n            (\n                status = 'success'\n                AND completed_at IS NOT NULL\n                AND error_code IS NULL\n                AND dimensions IS NOT NULL\n            )\n            OR\n            (\n                status IN ('failed', 'timeout')\n                AND completed_at IS NOT NULL\n                AND error_code IS NOT NULL\n            )\n            ", name=op.f('ck_embedding_calls_valid_lifecycle_state')),
    sa.CheckConstraint("\n            purpose IN (\n                'query',\n                'document_ingestion',\n                'reindex',\n                'evaluation',\n                'other'\n            )\n            ", name=op.f('ck_embedding_calls_valid_purpose')),
    sa.CheckConstraint("\n            status IN (\n                'started',\n                'success',\n                'failed',\n                'timeout'\n            )\n            ", name=op.f('ck_embedding_calls_valid_status')),
    sa.CheckConstraint('\n            completed_at IS NULL\n            OR completed_at >= started_at\n            ', name=op.f('ck_embedding_calls_valid_completion_time')),
    sa.CheckConstraint('\n            dimensions IS NULL\n            OR dimensions > 0\n            ', name=op.f('ck_embedding_calls_positive_dimensions')),
    sa.CheckConstraint('\n            latency_ms IS NULL\n            OR latency_ms >= 0\n            ', name=op.f('ck_embedding_calls_non_negative_latency')),
    sa.CheckConstraint('input_count > 0', name=op.f('ck_embedding_calls_positive_input_count')),
    sa.CheckConstraint('total_input_characters >= 0', name=op.f('ck_embedding_calls_non_negative_input_characters')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_embedding_calls_ai_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_version_id'], ['knowledge.knowledge_document_versions.id'], name=op.f('fk_embedding_calls_knowledge_version_id_knowledge_document_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_calls')),
    schema='ai'
    )
    op.create_index('idx_embedding_calls_ai_run', 'embedding_calls', ['ai_run_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_error_started', 'embedding_calls', ['error_code', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_latency', 'embedding_calls', [sa.literal_column('latency_ms DESC')], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_provider_started', 'embedding_calls', ['provider', 'model', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_purpose_started', 'embedding_calls', ['purpose', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_status_started', 'embedding_calls', ['status', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_trace', 'embedding_calls', ['trace_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_embedding_calls_version', 'embedding_calls', ['knowledge_version_id', 'started_at'], unique=False, schema='ai')
    op.create_table('stage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('trigger_message_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                event_type = 'stage_started'\n                AND duration_ms IS NULL\n                AND error_code IS NULL\n                AND retryable IS NULL\n            )\n            OR\n            (\n                event_type = 'stage_completed'\n                AND error_code IS NULL\n                AND retryable IS NULL\n            )\n            OR\n            (\n                event_type = 'stage_failed'\n                AND error_code IS NOT NULL\n                AND retryable IS NOT NULL\n            )\n            ", name=op.f('ck_stage_events_valid_event_payload')),
    sa.CheckConstraint("\n            event_type IN (\n                'stage_started',\n                'stage_completed',\n                'stage_failed'\n            )\n            ", name=op.f('ck_stage_events_valid_event_type')),
    sa.CheckConstraint("\n            stage IN (\n                'received',\n                'context_built',\n                'intent_classified',\n                'decision_made',\n                'retrieval_completed',\n                'response_generated',\n                'guardrails_completed',\n                'action_proposed',\n                'action_completed',\n                'escalated',\n                'completed',\n                'failed'\n            )\n            ", name=op.f('ck_stage_events_valid_stage')),
    sa.CheckConstraint('\n            duration_ms IS NULL\n            OR duration_ms >= 0\n            ', name=op.f('ck_stage_events_non_negative_duration')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_stage_events_ai_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_events')),
    schema='ai'
    )
    op.create_index('idx_ai_stage_events_conversation_occurred', 'stage_events', ['conversation_id', sa.literal_column('occurred_at DESC')], unique=False, schema='ai')
    op.create_index('idx_ai_stage_events_error_occurred', 'stage_events', ['error_code', sa.literal_column('occurred_at DESC')], unique=False, schema='ai')
    op.create_index('idx_ai_stage_events_run_occurred', 'stage_events', ['ai_run_id', 'occurred_at'], unique=False, schema='ai')
    op.create_index('idx_ai_stage_events_stage_occurred', 'stage_events', ['stage', sa.literal_column('occurred_at DESC')], unique=False, schema='ai')
    op.create_index('idx_ai_stage_events_trace_occurred', 'stage_events', ['trace_id', 'occurred_at'], unique=False, schema='ai')
    op.create_index('idx_ai_stage_events_type_occurred', 'stage_events', ['event_type', sa.literal_column('occurred_at DESC')], unique=False, schema='ai')
    op.create_table('retrieval_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('ai_run_id', sa.UUID(), nullable=True),
    sa.Column('embedding_call_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('retrieval_mode', sa.String(length=32), nullable=False),
    sa.Column('profile_identity', sa.String(length=255), nullable=False),
    sa.Column('configuration_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('query_character_count', sa.Integer(), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('vector_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lexical_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fused_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reranked_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('selected_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('context_block_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('context_token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reranker_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('context_truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('zero_result', sa.Boolean(), nullable=True),
    sa.Column('vector_latency_ms', sa.Integer(), nullable=True),
    sa.Column('lexical_latency_ms', sa.Integer(), nullable=True),
    sa.Column('fusion_latency_ms', sa.Integer(), nullable=True),
    sa.Column('reranker_latency_ms', sa.Integer(), nullable=True),
    sa.Column('context_build_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'started'\n                AND completed_at IS NULL\n                AND total_latency_ms IS NULL\n                AND zero_result IS NULL\n                AND error_code IS NULL\n            )\n            OR\n            (\n                status = 'success'\n                AND completed_at IS NOT NULL\n                AND total_latency_ms IS NOT NULL\n                AND zero_result IS NOT NULL\n                AND error_code IS NULL\n            )\n            OR\n            (\n                status IN ('failed', 'timeout')\n                AND completed_at IS NOT NULL\n                AND total_latency_ms IS NOT NULL\n                AND error_code IS NOT NULL\n            )\n            ", name=op.f('ck_retrieval_runs_valid_lifecycle_state')),
    sa.CheckConstraint("\n            retrieval_mode IN (\n                'vector',\n                'lexical',\n                'hybrid'\n            )\n            ", name=op.f('ck_retrieval_runs_valid_retrieval_mode')),
    sa.CheckConstraint("\n            status IN (\n                'started',\n                'success',\n                'failed',\n                'timeout'\n            )\n            ", name=op.f('ck_retrieval_runs_valid_status')),
    sa.CheckConstraint('\n            completed_at IS NULL\n            OR completed_at >= started_at\n            ', name=op.f('ck_retrieval_runs_valid_completion_time')),
    sa.CheckConstraint('\n            context_build_latency_ms IS NULL\n            OR context_build_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_context_latency')),
    sa.CheckConstraint('\n            fusion_latency_ms IS NULL\n            OR fusion_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_fusion_latency')),
    sa.CheckConstraint('\n            lexical_latency_ms IS NULL\n            OR lexical_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_lexical_latency')),
    sa.CheckConstraint('\n            reranker_latency_ms IS NULL\n            OR reranker_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_reranker_latency')),
    sa.CheckConstraint('\n            total_latency_ms IS NULL\n            OR total_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_total_latency')),
    sa.CheckConstraint('\n            vector_latency_ms IS NULL\n            OR vector_latency_ms >= 0\n            ', name=op.f('ck_retrieval_runs_non_negative_vector_latency')),
    sa.CheckConstraint('\n            zero_result IS NULL\n            OR zero_result = (selected_candidate_count = 0)\n            ', name=op.f('ck_retrieval_runs_valid_zero_result')),
    sa.CheckConstraint('context_block_count >= 0', name=op.f('ck_retrieval_runs_non_negative_context_blocks')),
    sa.CheckConstraint('context_token_count >= 0', name=op.f('ck_retrieval_runs_non_negative_context_tokens')),
    sa.CheckConstraint('fused_candidate_count >= 0', name=op.f('ck_retrieval_runs_non_negative_fused_candidates')),
    sa.CheckConstraint('lexical_candidate_count >= 0', name=op.f('ck_retrieval_runs_non_negative_lexical_candidates')),
    sa.CheckConstraint('query_character_count >= 0', name=op.f('ck_retrieval_runs_non_negative_query_characters')),
    sa.CheckConstraint('requested_limit > 0', name=op.f('ck_retrieval_runs_positive_requested_limit')),
    sa.CheckConstraint('reranked_candidate_count >= 0', name=op.f('ck_retrieval_runs_non_negative_reranked_candidates')),
    sa.CheckConstraint('selected_candidate_count >= 0', name=op.f('ck_retrieval_runs_non_negative_selected_candidates')),
    sa.CheckConstraint('vector_candidate_count >= 0', name=op.f('ck_retrieval_runs_non_negative_vector_candidates')),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai.runs.id'], name=op.f('fk_retrieval_runs_ai_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['embedding_call_id'], ['ai.embedding_calls.id'], name=op.f('fk_retrieval_runs_embedding_call_id_embedding_calls'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_runs')),
    schema='ai'
    )
    op.create_index('idx_retrieval_runs_ai_run_started', 'retrieval_runs', ['ai_run_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_conversation_started', 'retrieval_runs', ['conversation_id', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_latency', 'retrieval_runs', [sa.literal_column('total_latency_ms DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_mode_started', 'retrieval_runs', ['retrieval_mode', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_profile_started', 'retrieval_runs', ['profile_identity', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_status_started', 'retrieval_runs', ['status', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_trace_started', 'retrieval_runs', ['trace_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_retrieval_runs_zero_result_started', 'retrieval_runs', ['zero_result', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_table('reranker_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('retrieval_run_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=True),
    sa.Column('reranker_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('revision', sa.String(length=200), nullable=True),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('input_candidate_count', sa.Integer(), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('output_candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'started'\n                AND completed_at IS NULL\n                AND latency_ms IS NULL\n                AND error_code IS NULL\n            )\n            OR\n            (\n                status = 'success'\n                AND completed_at IS NOT NULL\n                AND latency_ms IS NOT NULL\n                AND error_code IS NULL\n            )\n            OR\n            (\n                status IN ('failed', 'timeout')\n                AND completed_at IS NOT NULL\n                AND latency_ms IS NOT NULL\n                AND error_code IS NOT NULL\n            )\n            ", name=op.f('ck_reranker_calls_valid_lifecycle_state')),
    sa.CheckConstraint("\n            status IN (\n                'started',\n                'success',\n                'failed',\n                'timeout'\n            )\n            ", name=op.f('ck_reranker_calls_valid_status')),
    sa.CheckConstraint('\n            completed_at IS NULL\n            OR completed_at >= started_at\n            ', name=op.f('ck_reranker_calls_valid_completion_time')),
    sa.CheckConstraint('\n            latency_ms IS NULL\n            OR latency_ms >= 0\n            ', name=op.f('ck_reranker_calls_non_negative_latency')),
    sa.CheckConstraint('\n            output_candidate_count\n            <= input_candidate_count\n            ', name=op.f('ck_reranker_calls_valid_output_cardinality')),
    sa.CheckConstraint('\n            output_candidate_count\n            <= requested_limit\n            ', name=op.f('ck_reranker_calls_output_within_requested_limit')),
    sa.CheckConstraint('input_candidate_count >= 0', name=op.f('ck_reranker_calls_non_negative_input_candidates')),
    sa.CheckConstraint('output_candidate_count >= 0', name=op.f('ck_reranker_calls_non_negative_output_candidates')),
    sa.CheckConstraint('requested_limit > 0', name=op.f('ck_reranker_calls_positive_requested_limit')),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['ai.retrieval_runs.id'], name=op.f('fk_reranker_calls_retrieval_run_id_retrieval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reranker_calls')),
    schema='ai'
    )
    op.create_index('idx_reranker_calls_error_started', 'reranker_calls', ['error_code', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_identity_started', 'reranker_calls', ['reranker_id', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_latency', 'reranker_calls', [sa.literal_column('latency_ms DESC')], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_provider_started', 'reranker_calls', ['provider', 'model', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_retrieval_run', 'reranker_calls', ['retrieval_run_id', 'started_at'], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_status_started', 'reranker_calls', ['status', sa.literal_column('started_at DESC')], unique=False, schema='ai')
    op.create_index('idx_reranker_calls_trace', 'reranker_calls', ['trace_id', 'started_at'], unique=False, schema='ai')
    op.create_table('retrieval_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('retrieval_run_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('vector_rank', sa.Integer(), nullable=True),
    sa.Column('lexical_rank', sa.Integer(), nullable=True),
    sa.Column('fusion_rank', sa.Integer(), nullable=True),
    sa.Column('reranker_rank', sa.Integer(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('vector_similarity', sa.Float(), nullable=True),
    sa.Column('lexical_score', sa.Float(), nullable=True),
    sa.Column('fusion_score', sa.Float(), nullable=True),
    sa.Column('reranker_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('selected_for_context', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            final_rank IS NULL\n            OR final_rank > 0\n            ', name=op.f('ck_retrieval_candidates_positive_final_rank')),
    sa.CheckConstraint('\n            final_score IS NULL\n            OR final_score >= 0\n            ', name=op.f('ck_retrieval_candidates_non_negative_final_score')),
    sa.CheckConstraint('\n            fusion_rank IS NULL\n            OR fusion_rank > 0\n            ', name=op.f('ck_retrieval_candidates_positive_fusion_rank')),
    sa.CheckConstraint('\n            fusion_score IS NULL\n            OR fusion_score >= 0\n            ', name=op.f('ck_retrieval_candidates_non_negative_fusion_score')),
    sa.CheckConstraint('\n            lexical_rank IS NULL\n            OR lexical_rank > 0\n            ', name=op.f('ck_retrieval_candidates_positive_lexical_rank')),
    sa.CheckConstraint('\n            lexical_score IS NULL\n            OR lexical_score >= 0\n            ', name=op.f('ck_retrieval_candidates_non_negative_lexical_score')),
    sa.CheckConstraint('\n            reranker_rank IS NULL\n            OR reranker_rank > 0\n            ', name=op.f('ck_retrieval_candidates_positive_reranker_rank')),
    sa.CheckConstraint('\n            reranker_score IS NULL\n            OR reranker_score >= 0\n            ', name=op.f('ck_retrieval_candidates_non_negative_reranker_score')),
    sa.CheckConstraint('\n            selected_for_context = false\n            OR final_rank IS NOT NULL\n            ', name=op.f('ck_retrieval_candidates_selected_candidate_has_final_rank')),
    sa.CheckConstraint('\n            vector_rank IS NOT NULL\n            OR lexical_rank IS NOT NULL\n            ', name=op.f('ck_retrieval_candidates_has_retrieval_origin')),
    sa.CheckConstraint('\n            vector_rank IS NULL\n            OR vector_rank > 0\n            ', name=op.f('ck_retrieval_candidates_positive_vector_rank')),
    sa.CheckConstraint('\n            vector_similarity IS NULL\n            OR (\n                vector_similarity >= -1\n                AND vector_similarity <= 1\n            )\n            ', name=op.f('ck_retrieval_candidates_valid_vector_similarity')),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['ai.retrieval_runs.id'], name=op.f('fk_retrieval_candidates_retrieval_run_id_retrieval_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_candidates')),
    sa.UniqueConstraint('retrieval_run_id', 'chunk_id', name='uq_retrieval_candidates_run_chunk'),
    schema='ai'
    )
    op.create_index('idx_retrieval_candidates_chunk', 'retrieval_candidates', ['chunk_id'], unique=False, schema='ai')
    op.create_index('idx_retrieval_candidates_document', 'retrieval_candidates', ['document_id'], unique=False, schema='ai')
    op.create_index('idx_retrieval_candidates_final_score', 'retrieval_candidates', [sa.literal_column('final_score DESC')], unique=False, schema='ai')
    op.create_index('idx_retrieval_candidates_run_final_rank', 'retrieval_candidates', ['retrieval_run_id', 'final_rank'], unique=False, schema='ai')
    op.create_index('idx_retrieval_candidates_run_selected', 'retrieval_candidates', ['retrieval_run_id', 'selected_for_context'], unique=False, schema='ai')
    op.create_index('idx_retrieval_candidates_version', 'retrieval_candidates', ['version_id'], unique=False, schema='ai')
    op.drop_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_content_not_blank'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_nonnegative_index'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_positive_token_count'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_timestamp_order'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_valid_offsets'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_chunks_content_not_blank'), 'knowledge_chunks', 'length(btrim(content)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_nonnegative_index'), 'knowledge_chunks', 'chunk_index >= 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_positive_token_count'), 'knowledge_chunks', 'token_count IS NULL OR token_count > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_timestamp_order'), 'knowledge_chunks', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_valid_offsets'), 'knowledge_chunks', '\n            (\n                start_offset IS NULL\n                AND end_offset IS NULL\n            )\n            OR\n            (\n                start_offset IS NOT NULL\n                AND end_offset IS NOT NULL\n                AND start_offset >= 0\n                AND end_offset > start_offset\n            )\n            ', schema='knowledge')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_027a'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_2b77'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_37cb'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_6738'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_9acc'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_b7ae'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_bd1b'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_content_not_blank'), 'knowledge_document_versions', 'length(btrim(source_content)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_hash_not_blank'), 'knowledge_document_versions', 'length(btrim(content_hash)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ingestion_status'), 'knowledge_document_versions', "ingestion_status IN ('pending', 'running', 'completed', 'failed')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_positive_version'), 'knowledge_document_versions', 'version_number > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_source_type'), 'knowledge_document_versions', "source_type IN ('markdown', 'plain_text', 'pdf', 'docx', 'html', 'rich_text')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_status'), 'knowledge_document_versions', "status IN ('draft', 'processing', 'ready', 'published', 'superseded', 'failed', 'archived')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_timestamp_order'), 'knowledge_document_versions', 'updated_at >= created_at', schema='knowledge')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_archived_at_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_content_type'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_deleted_at_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_lifecycle'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_status'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_timestamp_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_title_not_blank'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_visibility'), 'knowledge_documents', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_documents_archived_at_order'), 'knowledge_documents', 'archived_at IS NULL OR archived_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_content_type'), 'knowledge_documents', "content_type IN ('policy', 'faq', 'procedure', 'guide', 'reference', 'other')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_deleted_at_order'), 'knowledge_documents', 'deleted_at IS NULL OR deleted_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_lifecycle'), 'knowledge_documents', "\n            (\n                status = 'active'\n                AND archived_at IS NULL\n                AND deleted_at IS NULL\n            )\n            OR\n            (\n                status = 'archived'\n                AND archived_at IS NOT NULL\n                AND deleted_at IS NULL\n            )\n            OR\n            (\n                status = 'deleted'\n                AND deleted_at IS NOT NULL\n            )\n            ", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_status'), 'knowledge_documents', "status IN ('active', 'archived', 'deleted')", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_timestamp_order'), 'knowledge_documents', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_title_not_blank'), 'knowledge_documents', 'length(btrim(title)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_visibility'), 'knowledge_documents', "visibility IN ('customer', 'internal', 'both')", schema='knowledge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_knowledge_documents_visibility'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_title_not_blank'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_timestamp_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_status'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_lifecycle'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_deleted_at_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_content_type'), 'knowledge_documents', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_documents_archived_at_order'), 'knowledge_documents', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_visibility'), 'knowledge_documents', "visibility::text = ANY (ARRAY['customer'::character varying, 'internal'::character varying, 'both'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_title_not_blank'), 'knowledge_documents', 'length(btrim(title::text)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_timestamp_order'), 'knowledge_documents', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_status'), 'knowledge_documents', "status::text = ANY (ARRAY['active'::character varying, 'archived'::character varying, 'deleted'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_lifecycle'), 'knowledge_documents', "status::text = 'active'::text AND archived_at IS NULL AND deleted_at IS NULL OR status::text = 'archived'::text AND archived_at IS NOT NULL AND deleted_at IS NULL OR status::text = 'deleted'::text AND deleted_at IS NOT NULL", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_deleted_at_order'), 'knowledge_documents', 'deleted_at IS NULL OR deleted_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_content_type'), 'knowledge_documents', "content_type::text = ANY (ARRAY['policy'::character varying, 'faq'::character varying, 'procedure'::character varying, 'guide'::character varying, 'reference'::character varying, 'other'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_documents_ck_knowledge_documents_archived_at_order'), 'knowledge_documents', 'archived_at IS NULL OR archived_at >= created_at', schema='knowledge')
    op.drop_constraint(op.f('ck_knowledge_document_versions_timestamp_order'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_status'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_source_type'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_positive_version'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_ingestion_status'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_hash_not_blank'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_document_versions_content_not_blank'), 'knowledge_document_versions', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_bd1b'), 'knowledge_document_versions', "status::text = ANY (ARRAY['draft'::character varying, 'processing'::character varying, 'ready'::character varying, 'published'::character varying, 'superseded'::character varying, 'failed'::character varying, 'archived'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_b7ae'), 'knowledge_document_versions', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_9acc'), 'knowledge_document_versions', 'version_number > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_6738'), 'knowledge_document_versions', "ingestion_status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])", schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_37cb'), 'knowledge_document_versions', 'length(btrim(content_hash::text)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_2b77'), 'knowledge_document_versions', 'length(btrim(source_content)) > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_document_versions_ck_knowledge_document_ve_027a'), 'knowledge_document_versions', "source_type::text = ANY (ARRAY['markdown'::character varying, 'plain_text'::character varying, 'pdf'::character varying, 'docx'::character varying, 'html'::character varying, 'rich_text'::character varying]::text[])", schema='knowledge')
    op.drop_constraint(op.f('ck_knowledge_chunks_valid_offsets'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_timestamp_order'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_positive_token_count'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_nonnegative_index'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.drop_constraint(op.f('ck_knowledge_chunks_content_not_blank'), 'knowledge_chunks', schema='knowledge', type_='check')
    op.create_check_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_valid_offsets'), 'knowledge_chunks', 'start_offset IS NULL AND end_offset IS NULL OR start_offset IS NOT NULL AND end_offset IS NOT NULL AND start_offset >= 0 AND end_offset > start_offset', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_timestamp_order'), 'knowledge_chunks', 'updated_at >= created_at', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_positive_token_count'), 'knowledge_chunks', 'token_count IS NULL OR token_count > 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_nonnegative_index'), 'knowledge_chunks', 'chunk_index >= 0', schema='knowledge')
    op.create_check_constraint(op.f('ck_knowledge_chunks_ck_knowledge_chunks_content_not_blank'), 'knowledge_chunks', 'length(btrim(content)) > 0', schema='knowledge')
    op.drop_index('idx_retrieval_candidates_version', table_name='retrieval_candidates', schema='ai')
    op.drop_index('idx_retrieval_candidates_run_selected', table_name='retrieval_candidates', schema='ai')
    op.drop_index('idx_retrieval_candidates_run_final_rank', table_name='retrieval_candidates', schema='ai')
    op.drop_index('idx_retrieval_candidates_final_score', table_name='retrieval_candidates', schema='ai')
    op.drop_index('idx_retrieval_candidates_document', table_name='retrieval_candidates', schema='ai')
    op.drop_index('idx_retrieval_candidates_chunk', table_name='retrieval_candidates', schema='ai')
    op.drop_table('retrieval_candidates', schema='ai')
    op.drop_index('idx_reranker_calls_trace', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_status_started', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_retrieval_run', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_provider_started', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_latency', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_identity_started', table_name='reranker_calls', schema='ai')
    op.drop_index('idx_reranker_calls_error_started', table_name='reranker_calls', schema='ai')
    op.drop_table('reranker_calls', schema='ai')
    op.drop_index('idx_retrieval_runs_zero_result_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_trace_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_status_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_profile_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_mode_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_latency', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_conversation_started', table_name='retrieval_runs', schema='ai')
    op.drop_index('idx_retrieval_runs_ai_run_started', table_name='retrieval_runs', schema='ai')
    op.drop_table('retrieval_runs', schema='ai')
    op.drop_index('idx_ai_stage_events_type_occurred', table_name='stage_events', schema='ai')
    op.drop_index('idx_ai_stage_events_trace_occurred', table_name='stage_events', schema='ai')
    op.drop_index('idx_ai_stage_events_stage_occurred', table_name='stage_events', schema='ai')
    op.drop_index('idx_ai_stage_events_run_occurred', table_name='stage_events', schema='ai')
    op.drop_index('idx_ai_stage_events_error_occurred', table_name='stage_events', schema='ai')
    op.drop_index('idx_ai_stage_events_conversation_occurred', table_name='stage_events', schema='ai')
    op.drop_table('stage_events', schema='ai')
    op.drop_index('idx_embedding_calls_version', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_trace', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_status_started', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_purpose_started', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_provider_started', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_latency', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_error_started', table_name='embedding_calls', schema='ai')
    op.drop_index('idx_embedding_calls_ai_run', table_name='embedding_calls', schema='ai')
    op.drop_table('embedding_calls', schema='ai')
    # ### end Alembic commands ###
