## This file define the provider-neutral result contract
from __future__ import annotations
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Generic, TypeVar
from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)

@dataclass(frozen=True, slots=True)
class TokenUsage:
    """
    Normalized token-usage information returned by an LLM provider.

    Provider SDKs expose usage differently. This object gives the rest of
    the application one stable representation.

    Semantics:
    - input_tokens:
        Total prompt/input tokens reported by the provider.
    - output_tokens:
        Tokens generated by the model.
    - cached_input_tokens:
        Portion of input tokens served from provider-side cache, if known.
    - total_tokens:
        Canonical total for this application: input + output.

    Cached tokens are not added again to total_tokens because they are
    normally already a subset of input_tokens.
    """
    input_tokens: int = 0
    output_tokens: int = 0
    cached_input_tokens: int = 0

    def __post_init__(self) -> None:
        for name, value in (
            ("input_tokens", self.input_tokens),
            ("output_tokens", self.output_tokens),
            ("cached_input_tokens", self.cached_input_tokens),
        ):
            if isinstance(value, bool) or not isinstance(value, int):
                raise TypeError(f"{name} must be an integer")

            if value < 0:
                raise ValueError(f"{name} cannot be negative")

        if self.cached_input_tokens > self.input_tokens:
            raise ValueError("cached_input_tokens cannot exceed input_tokens")

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass(frozen=True, slots=True)
class ProviderMetadata:
    """
    Provider-specific metadata that is useful for debugging and correlation.

    Keep this deliberately small and normalized. Raw provider payloads should
    not leak throughout the application.
    """
    provider_request_id: str | None = None
    finish_reason: str | None = None
    raw_model_name: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "provider_request_id", _normalize_optional_string(self.provider_request_id))
        object.__setattr__(self, "finish_reason", _normalize_optional_string(self.finish_reason))
        object.__setattr__(self, "raw_model_name", _normalize_optional_string(self.raw_model_name))


@dataclass(frozen=True, slots=True)
class LLMResponse:
    """
    Normalized result of a plain-text LLM invocation.
    """
    content: str
    provider: str
    model: str
    usage: TokenUsage = field(default_factory=TokenUsage)
    metadata: ProviderMetadata = field(default_factory=ProviderMetadata)
    estimated_cost_usd: Decimal | None = None

    def __post_init__(self) -> None:
        normalized_content = _normalize_required_string(self.content, field_name="content")
        normalized_provider = _normalize_required_string(self.provider, field_name="provider")
        normalized_model = _normalize_required_string(self.model, field_name="model")

        object.__setattr__(self, "content", normalized_content)
        object.__setattr__(self, "provider", normalized_provider)
        object.__setattr__(self, "model", normalized_model)

        _validate_cost(self.estimated_cost_usd)


@dataclass(frozen=True, slots=True)
class StructuredLLMResponse(Generic[T]):
    """
    Normalized result of a structured LLM invocation.

    `output` is already validated against the requested Pydantic response
    model by the provider adapter.

    Example:

        StructuredLLMResponse[IntentResult](
            output=intent_result,
            provider="groq",
            model="...",
            usage=...,
            metadata=...,
        )
    """

    output: T
    provider: str
    model: str
    usage: TokenUsage = field(default_factory=TokenUsage)
    metadata: ProviderMetadata = field(default_factory=ProviderMetadata)
    estimated_cost_usd: Decimal | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.output, BaseModel):
            raise TypeError("output must be a Pydantic BaseModel instance")

        normalized_provider = _normalize_required_string(self.provider, field_name="provider")
        normalized_model = _normalize_required_string(self.model, field_name="model")

        object.__setattr__(self, "provider", normalized_provider)
        object.__setattr__(self, "model", normalized_model)

        _validate_cost(self.estimated_cost_usd)


def _normalize_required_string(value: str, *, field_name: str) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be a string")

    normalized = value.strip()
    if not normalized:
        raise ValueError(f"{field_name} cannot be empty")

    return normalized


def _normalize_optional_string(value: str | None) -> str | None:
    if value is None:
        return None

    if not isinstance(value, str):
        raise TypeError("optional metadata values must be strings or None")

    normalized = value.strip()
    return normalized or None


def _validate_cost(value: Decimal | None) -> None:
    if value is None:
        return

    if not isinstance(value, Decimal):
        raise TypeError("estimated_cost_usd must be Decimal or None")

    if value < 0:
        raise ValueError("estimated_cost_usd cannot be negative")